config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  mount Sidekiq::Web => '/sidekiq'

  scope module: :api, defaults: { format: :json } do
    %w(v1).each do |version|
      namespace version do
        resources :jobs do
          post :webhook
        end
      end
    end
  end

  resources :apps, shallow: true do
    resources :job_profiles, path: :profiles
    resources :jobs
  end

  controller :welcome do
    get :dashboard
  end

  root 'welcome#index'
end

app/models/app.rb
class App < ApplicationRecord
  belongs_to :user
  has_many :jobs, class_name: 'TranscodingJob'
  has_many :profiles, class_name: 'JobProfile'

  attr_encrypted :s3_access_key_id, key: -> (_) { Rails.application.secrets.encryption_key }
  attr_encrypted :s3_secret_access_key, key: -> (_) { Rails.application.secrets.encryption_key }

  validates :name, presence: true
  validates :url, presence: true

  before_create :generate_access_token, :generate_s3_output_bucket
  after_create :s3_tasks

  def generate_s3_output_bucket
    self.s3_output_bucket = SecureRandom.uuid
  end

  def s3_tasks
    app_manager = AppManager.new(self)
    app_manager.create_bucket!
    app_manager.put_cors_policy!
  end

  def generate_access_token
    self.access_token ||= loop do
      token = Devise.friendly_token
      break token unless self.class.exists?(access_token: token)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job_profile.rb
class JobProfile < ApplicationRecord
  belongs_to :app
end

app/models/transcoding_job.rb
class TranscodingJob < ApplicationRecord
  include AASM

  belongs_to :app

  validates :input, presence: true, url: true
  validates :webhook_url, presence: true, url: true

  after_create :enqueue_job

  enum state: %i(created processing completed failed)

  aasm column: :state, enum: true do
    state :created, initial: true
    state :processing
    state :completed
    state :failed
    state :pending

    event :process do
      transitions from: :created, to: :processing
    end

    event :complete, after_commit: :send_success_webhook do
      transitions from: :processing, to: :completed
    end

    event :fail do
      transitions from: :processing, to: :failed
    end
  end

  def local_pathname
    token = [app.id, id, created_at, input].join('/')
    Digest::MD5.hexdigest(token)
  end

  private

  def send_success_webhook
    return unless completed?
    JobSuccessWebhookJob.perform_later(self)
  end

  def enqueue_job
    return if completed?
    ProcessTranscodingJob.perform_later(self)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :apps
  has_many :jobs, through: :apps

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  attr_accessor :current_app

  protect_from_forgery with: :exception
  before_action :requires_authentication_token
  skip_before_action :verify_authenticity_token,
                     if: -> (c) { c.request.format == 'application/json' }

  def requires_authentication_token
    authenticate_or_request_with_http_token do |token|
      @current_app ||= App.find_by(access_token: token)
      if current_app
        true
      else
        false
      end
    end
  end
end

app/controllers/api/v1/jobs_controller.rb
class Api::V1::JobsController < Api::V1::BaseController
  skip_before_action :requires_authentication_token, only: %w(webhook)

  def index
  end

  def create
    job = current_app.jobs.new(job_params)
    if job.valid?
      job.save
      render json: {
        job: job
      }, status: :created
    else
      render json: {
        errors: job.errors.full_messages
      }, status: :unprocessable_entity
    end
  end

  def webhook
    puts JSON.parse(params[:job]).inspect
    head :ok
  end

  private

  def job_params
    params.require(:job).permit :input, :webhook_url, profiles: [], override: {}
  end
end

# TranscoderHero::Job.create(
#   input: 'https://s3.amazonaws.com/vdb-submit-media-staging/video/d7bf18225e7e92ed963115bae575ec26a2420e33.mov',
#   profiles: ['Virtual Diamond Resize', 'Virtual Diamond Crop', 'Extract Frames'],
#   override: {
#     crop: {
#       w: 1080,
#       h: 1080,
#       left: 420,
#       top: 0
#     },
#     scale: {
#       width: 600,
#       height: 600
#     }
#   }
# )

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :load_app, only: %w(show edit update set_default)

  def index
    @apps = current_user.apps
  end

  def show
  end

  def new
    @app = App.new
  end

  def edit
  end

  def update
    if @app.update app_params
      redirect_to app_path(@app), notice: 'App updated successfully!'
    else
      render :edit
    end
  end

  def create
    @app = current_user.apps.new app_params

    if @app.valid?
      @app.save
      redirect_to apps_path, notice: 'App created successfully!'
    else
      render :edit
    end
  end

  private

  def load_app
    @app = current_user.apps.find(params[:id])
  end

  def app_params
    params.require(:app).permit :name, :url, :s3_access_key_id,
                                :s3_secret_access_key
  end
end

app/controllers/job_profiles_controller.rb
class JobProfilesController < ApplicationController
  before_action :load_app, only: %w(index)
  def index
    @profiles = @app.profiles
  end

  def new
    @profile = JobProfile.new
  end

  private

  def load_app
    @app = current_user.apps.find(params[:app_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end

  def dashboard
    @jobs = current_user.jobs
    @failed_jobs = @jobs.failed
    @completed_jobs = @jobs.completed
    @processing_jobs = @jobs.processing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_apps
    @apps ||= current_user.apps
  end
end

app/helpers/job_profiles_helper.rb
module JobProfilesHelper
end

app/views/apps/_form.html.haml
= form_for @app, html: { class: 'ui large form' } do |f|
  .field
    = f.label 'App name'
    .ui.massive.input
      = f.text_field :name
    %p Something to jog your memory 6 months from now
  .field
    = f.label 'App root url'
    .ui.labeled.input
      .ui.label http://
      = f.text_field :url, placeholder: 'facebook.com'
    %p ex: facebook.com

  .ui.section.divider
  %h3.ui.header Amazon S3
  .field
    = f.label 'Access Key ID'
    = f.text_field :s3_access_key_id

  .field
    = f.label 'Secret Access Key'
    = f.text_field :s3_secret_access_key

  %p
    Clicking the "Create App" button will connect to your S3 account and
    generate a bucket where we will output your transcoded videos & thumbnails.

  %button.ui.submit.button Create App

app/views/apps/edit.html.haml
.eight.wide.column
  = render partial: 'form'

app/views/apps/index.html.haml
.ui.container
  .sixteen.column
    %h3.ui.medium.header Your Apps

    .ui.segment.basic
      %p= link_to 'Add a new app', new_app_path

    %table.ui.celled.table
      %thead
        %tr
          %th Name
          %th Url
          %th
          %th
          %th
          %th
      %tbody
        - @apps.each do |app|
          %tr
            %td= app.name
            %td= app.url
            %td= link_to 'profiles', app_job_profiles_path(app)
            %td= link_to 'add profile', new_app_job_profile_path(app)
            %td= link_to 'view', app_path(app)
            %td= link_to 'edit', edit_app_path(app)

app/views/apps/new.html.haml
.ui.container
  .ui.grid
    .eight.wide.column
      %h3.ui.medium.header Create a new App
      = render partial: 'form'

app/views/apps/show.html.haml
.ui.container
  .ui.grid
    .sixteen.wide.column
      %h3.ui.huge.header= @app.name

      .ui.list
        .item
          .content
            .header Url
            .description= @app.url
        .item
          .content
            .header S3 Bucket Name
            .description= @app.s3_output_bucket
        .item
          .content
            .header Access token
            .description= @app.access_token
        .item
          .content
            .header Total Jobs
            .description= @app.jobs.count

app/views/job_profiles/_form.html.haml
= form_for [:app, @profile], html: { class: 'ui large form' } do |f|
  .field
    = f.label 'Profile name'
    = f.text_field :name
    %p Give your job profile a descriptive name. Ex: Activity Stream Videos

  %h4.ui.top.attached.header Platform Support
  .ui.attached.segment
    %p which platforms do you need to support?
    .ui.form
      .inline.field
        .ui.toggle.checkbox
          = check_box_tag 'platforms[]', :html5
          %label HTML5
      .inline.field
        .ui.toggle.checkbox
          = check_box_tag 'platforms[]', :ios
          %label iPhone
      .inline.field
        .ui.toggle.checkbox
          = check_box_tag 'platforms[]', :android
          %label Android

  %h4.ui.top.attached.header Video Quality
  .ui.attached.segment
    .ui.form
      .inline.field
        .ui.toggle.checkbox
          = check_box_tag :hd, true
          %label Support High Definition Playback? (HD)

  %h4.ui.top.attached.header Video Resize
  .ui.attached.segment
    %p Any transformations performed will always maintain aspect ratio.
    .ui.form
      .inline.fields
        .inline.field
          %label width
          = number_field_tag :width
        .inline.field
          %label height
          = number_field_tag :height

  %h4.ui.top.attached.header Video Crop
  .ui.attached.segment
    .ui.form
      .inline.field
        .ui.toggle.checkbox
          = check_box_tag :crop, :square
          %label Crop video as a square

  %h4.ui.top.attached.header Thumbnails
  .ui.attached.segment
    %p
      Thumbnails are created using the finalized video after any cropping
      and scaling is performed.
    .ui.form
      .inline.field
        .ui.toggle.checkbox
          = check_box_tag :thumbnails, :every
          %label Extract All Frames as Thumbnails

app/views/job_profiles/index.html.haml
.sixteen.wide.column
  %h3.ui.medium.header Job Profiles

app/views/job_profiles/new.html.haml
.ui.container
  .ui.grid
    .eight.wide.column
      %h3.ui.medium.header Add a Job Profile
      = render partial: 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MediaPlatform
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{ class: user_signed_in? ? 'signed-in' : '' }
    .ui.top.fixed.menu.main
      .ui.container
        .item
          = link_to root_path do
            = image_tag 'Transcoder-Hero.png', class: 'main-logo'

        - unless user_signed_in?
          .right.menu
            .item= link_to 'Sign up', new_user_registration_path
            .item= link_to 'Log in', new_user_session_path

        - if user_signed_in?
          .ui.dropdown.right.item
            = current_user.email
            .dropdown.icon
            .ui.vertical.menu
              .item= link_to 'Manage Apps', apps_path
              .item= link_to 'New App', new_app_path
              .item= link_to 'logout', destroy_user_session_path, method: :delete

    = yield

app/views/welcome/dashboard.html.haml
.ui.container
  .column.wide.sixteen
    .ui.segment
      .ui.four.statistics
        .statistic
          .value
            = @jobs.count
          .label
            Total #{'Job'.pluralize(@jobs.count)}
        .statistic
          .value
            = @completed_jobs.count
          .label
            Successful #{'Job'.pluralize(@completed_jobs.count)}
        .statistic
          .value
            = @failed_jobs.count
          .label
            Failed #{'Job'.pluralize(@failed_jobs.count)}
        .statistic
          .value
            = @processing_jobs.count
          .label
            Processing #{'Job'.pluralize(@processing_jobs.count)}

    %h2.ui.header Current Jobs
    %table.ui.celled.table
      %thead
        %tr
          %th Job ID
          %th Progress
      %tbody
        - @processing_jobs.each do |job|
          %tr
            %td= job.id
            %td
              .ui.indicating.green.progress{ data: { value: 0.5, total: 1.0 } }
                .bar

app/views/welcome/index.html.haml
.ui.inverted.vertical.masthead.center.aligned.segment
  .ui.text.container
    %h1.ui.inverted.header Video Transcoding
    %h2 The easy way.
    = link_to 'get started', '', class: 'ui huge button inverted'
.ui.vertical.stripe.segment
  .row
    .eight.wide.column
      %h3.ui.header